#!/usr/bin/env bash
# Create br0 bridge on the host's primary NIC so VMs can join the main network.
# Supports netplan (Ubuntu), NetworkManager (nmcli), and systemd-networkd (Arch). Must run as root.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root (use sudo)."
  exit 1
fi

BRIDGE_NAME="br0"

# --- Helpers ---
is_bridge() {
  [[ -d "/sys/class/net/${1}/bridge" ]]
}

is_interface_slave_of_bridge() {
  local iface="$1"
  local master
  if [[ -L "/sys/class/net/${iface}/master" ]]; then
    master="$(readlink -f "/sys/class/net/${iface}/master" 2>/dev/null)"
    master="$(basename "$master" 2>/dev/null)"
    if [[ -n "$master" ]] && is_bridge "$master"; then
      echo "$master"
      return 0
    fi
  fi
  return 1
}

has_non_virbr_bridge() {
  local name
  for name in /sys/class/net/*/bridge; do
    name="$(basename "$(dirname "$name")")"
    if [[ "$name" != virbr* ]]; then
      return 0
    fi
  done
  return 1
}

# --- 1. Detect primary interface from default route ---
PRIMARY_IFACE=""
while read -r _ _ _ _ iface _; do
  if [[ -n "$iface" ]] && [[ -d "/sys/class/net/$iface" ]]; then
    PRIMARY_IFACE="$iface"
    break
  fi
done < <(ip route show default 2>/dev/null || true)

if [[ -z "$PRIMARY_IFACE" ]]; then
  echo "ERROR: Could not detect primary network interface (no default route)."
  exit 1
fi

# --- 2. Skip if already a bridge or already enslaved ---
if is_bridge "$PRIMARY_IFACE"; then
  echo "Primary interface $PRIMARY_IFACE is already a bridge. Nothing to do."
  exit 0
fi

existing_bridge="$(is_interface_slave_of_bridge "$PRIMARY_IFACE" || true)"
if [[ -n "$existing_bridge" ]]; then
  echo "Primary interface $PRIMARY_IFACE is already in bridge $existing_bridge. Nothing to do."
  exit 0
fi

# --- 3. Skip if a non-virbr bridge already exists (e.g. br0) ---
if has_non_virbr_bridge && [[ -d "/sys/class/net/${BRIDGE_NAME}/bridge" ]]; then
  echo "Bridge $BRIDGE_NAME already exists. Nothing to do."
  exit 0
fi

# --- 4. Detect DHCP vs static on primary interface ---
DHCP4=false
if ip -4 addr show "$PRIMARY_IFACE" 2>/dev/null | grep -q "dynamic"; then
  DHCP4=true
fi

# --- 5. Detect config system and apply ---
if command -v netplan &>/dev/null && [[ -d /etc/netplan ]]; then
  # --- Netplan (Ubuntu) ---
  NETPLAN_FILE="/etc/netplan/90-wisp-bridge.yaml"
  echo "Using netplan. Writing $NETPLAN_FILE ..."

  if [[ "$DHCP4" == true ]]; then
    cat > "$NETPLAN_FILE" << EOF
# Generated by Wisp bridge.sh - bridged networking for VMs
network:
  version: 2
  ethernets:
    $PRIMARY_IFACE:
      dhcp4: false
  bridges:
    $BRIDGE_NAME:
      interfaces: [$PRIMARY_IFACE]
      dhcp4: true
      parameters:
        stp: false
        forward-delay: 0
EOF
  else
    # Static: read current address and gateway
    ADDR="$(ip -4 -o addr show "$PRIMARY_IFACE" 2>/dev/null | awk '{print $4}' | head -1)"
    GATEWAY="$(ip -4 route show default dev "$PRIMARY_IFACE" 2>/dev/null | awk '{print $3}' | head -1)"
    ROUTES=""
    if [[ -n "$GATEWAY" ]]; then
      ROUTES="routes:
        - to: default
          via: $GATEWAY"
    fi
    NAMESERVERS=""
    if [[ -f /run/systemd/resolve/resolv.conf ]]; then
      NS="$(grep '^nameserver ' /run/systemd/resolve/resolv.conf 2>/dev/null | awk '{print $2}' | head -3 | tr '\n' ',' | sed 's/,$//')"
      if [[ -n "$NS" ]]; then
        NAMESERVERS="nameservers:
          addresses: [$NS]"
      fi
    fi
    if [[ -z "$ADDR" ]]; then
      echo "ERROR: Could not read IPv4 address for $PRIMARY_IFACE (static config)."
      exit 1
    fi
    cat > "$NETPLAN_FILE" << EOF
# Generated by Wisp bridge.sh - bridged networking for VMs
network:
  version: 2
  ethernets:
    $PRIMARY_IFACE:
      dhcp4: false
  bridges:
    $BRIDGE_NAME:
      interfaces: [$PRIMARY_IFACE]
      addresses: [$ADDR]
      $ROUTES
      $NAMESERVERS
      parameters:
        stp: false
        forward-delay: 0
EOF
  fi

  chmod 600 "$NETPLAN_FILE"
  echo "  Config written (mode 600). Applying with 'netplan apply' (bridge/bond configs cannot use netplan try revert)."
  echo "  Ensure you have console access in case SSH drops during the apply."
  if ! netplan apply; then
    echo "  netplan apply failed."
    exit 1
  fi
elif command -v nmcli &>/dev/null && nmcli networking 2>/dev/null | grep -q "enabled"; then
  # --- NetworkManager (nmcli) ---
  echo "Using NetworkManager (nmcli). Creating bridge $BRIDGE_NAME with $PRIMARY_IFACE ..."
  CONN_BR="wisp-$BRIDGE_NAME"
  CONN_IFACE="wisp-$PRIMARY_IFACE"
  # Remove IP from existing connection on the interface, create bridge connection, add interface as bridge port
  nmcli connection add type bridge ifname "$BRIDGE_NAME" con-name "$CONN_BR" stp no 2>/dev/null || true
  nmcli connection modify "$CONN_BR" connection.interface-name "$BRIDGE_NAME"
  if [[ "$DHCP4" == true ]]; then
    nmcli connection modify "$CONN_BR" ipv4.method auto
  else
    ADDR="$(ip -4 -o addr show "$PRIMARY_IFACE" 2>/dev/null | awk '{print $4}' | head -1)"
    GATEWAY="$(ip -4 route show default 2>/dev/null | awk '{print $3}' | head -1)"
    nmcli connection modify "$CONN_BR" ipv4.method manual ipv4.addresses "$ADDR" ipv4.gateway "$GATEWAY" 2>/dev/null || true
  fi
  nmcli connection add type ethernet ifname "$PRIMARY_IFACE" con-name "$CONN_IFACE" master "$BRIDGE_NAME" 2>/dev/null || true
  nmcli connection down "$(nmcli -t -f NAME,DEVICE connection show --active | grep ":$PRIMARY_IFACE$" | cut -d: -f1)" 2>/dev/null || true
  nmcli connection up "$CONN_BR" 2>/dev/null || true
elif systemctl is-active --quiet systemd-networkd 2>/dev/null; then
  # --- systemd-networkd (Arch Linux and others) ---
  echo "Using systemd-networkd. Writing network config files..."
  NETDEV_FILE="/etc/systemd/network/90-wisp-${BRIDGE_NAME}.netdev"
  BRIDGE_NET_FILE="/etc/systemd/network/90-wisp-${BRIDGE_NAME}.network"
  IFACE_NET_FILE="/etc/systemd/network/90-wisp-${PRIMARY_IFACE}.network"

  # Bridge device definition
  cat > "$NETDEV_FILE" << EOF
# Generated by Wisp bridge.sh - bridged networking for VMs
[NetDev]
Name=$BRIDGE_NAME
Kind=bridge

[Bridge]
STP=no
ForwardDelaySec=0
EOF

  # Bridge network config (IP assignment)
  if [[ "$DHCP4" == true ]]; then
    cat > "$BRIDGE_NET_FILE" << EOF
# Generated by Wisp bridge.sh - bridged networking for VMs
[Match]
Name=$BRIDGE_NAME

[Network]
DHCP=ipv4
EOF
  else
    ADDR="$(ip -4 -o addr show "$PRIMARY_IFACE" 2>/dev/null | awk '{print $4}' | head -1)"
    GATEWAY="$(ip -4 route show default dev "$PRIMARY_IFACE" 2>/dev/null | awk '{print $3}' | head -1)"
    if [[ -z "$ADDR" ]]; then
      echo "ERROR: Could not read IPv4 address for $PRIMARY_IFACE (static config)."
      exit 1
    fi
    {
      echo "# Generated by Wisp bridge.sh - bridged networking for VMs"
      echo "[Match]"
      echo "Name=$BRIDGE_NAME"
      echo ""
      echo "[Network]"
      echo "Address=$ADDR"
      [[ -n "$GATEWAY" ]] && echo "Gateway=$GATEWAY"
      # Add DNS from systemd-resolved if available
      if [[ -f /run/systemd/resolve/resolv.conf ]]; then
        NS="$(grep '^nameserver ' /run/systemd/resolve/resolv.conf 2>/dev/null | awk '{print $2}' | head -3)"
        while IFS= read -r ns; do
          [[ -n "$ns" ]] && echo "DNS=$ns"
        done <<< "$NS"
      fi
    } > "$BRIDGE_NET_FILE"
  fi

  # Enslave physical interface to the bridge (higher prefix overrides existing config)
  cat > "$IFACE_NET_FILE" << EOF
# Generated by Wisp bridge.sh - bridged networking for VMs
[Match]
Name=$PRIMARY_IFACE

[Network]
Bridge=$BRIDGE_NAME
EOF

  echo "  Config written to /etc/systemd/network/. Restarting systemd-networkd..."
  echo "  SSH may briefly drop during the restart; reconnect if needed."
  systemctl restart systemd-networkd
else
  echo "ERROR: No supported network manager found (tried: netplan, NetworkManager/nmcli, systemd-networkd)."
  echo ""
  echo "To set up bridging manually:"
  echo "  1. Create bridge $BRIDGE_NAME and add $PRIMARY_IFACE as a port using your network manager."
  echo "  2. Set WISP_DEFAULT_BRIDGE=br0 in config/runtime.env and restart Wisp."
  echo ""
  echo "For systemd-networkd (common on Arch): enable it with 'sudo systemctl enable --now systemd-networkd',"
  echo "  then re-run this script."
  exit 1
fi

# --- 6. Verify bridge exists ---
if [[ ! -d "/sys/class/net/${BRIDGE_NAME}/bridge" ]]; then
  echo "ERROR: Bridge $BRIDGE_NAME was not created."
  exit 1
fi
echo "  Bridge $BRIDGE_NAME is up."

# --- 7. Disable and stop libvirt default NAT network ---
if virsh net-info default &>/dev/null; then
  virsh net-autostart default --disable 2>/dev/null && echo "  Libvirt default (NAT) network disabled from autostart." || true
  virsh net-destroy default 2>/dev/null && echo "  Default NAT network stopped (virbr0 removed)." || true
fi

echo "Done. VMs can use bridge $BRIDGE_NAME to join the host network."
