#!/usr/bin/env bash
# Set up the stub IP + container resolv.conf used by Wisp's in-process DNS
# forwarder (backend/src/lib/mdns/linux/forwarder.js).
#
# How it works:
#   - Give br0 the link-local 169.254.53.53/32. The wisp process
#     binds UDP+TCP 53 on this IP (via CAP_NET_BIND_SERVICE) and answers
#     container DNS queries: `.local` names go to avahi over DBus,
#     everything else is forwarded to the host's upstream DNS.
#   - Drop a ready-to-bind-mount resolv.conf so Wisp containers on br0
#     use the stub IP as their sole nameserver.
#
# The stub IP is DECLARED to systemd-networkd through a drop-in on whichever
# .network unit manages br0, so networkd re-applies it after a restart or a
# `networkctl reconfigure` instead of flushing it as a foreign address. It used
# to be runtime-only, and any networkd restart (an unattended systemd upgrade
# is enough) silently killed all container DNS: the address goes away, wisp's
# socket stays bound to it, and every query black-holes until wisp restarts.
# A networkd drop-in bypasses netplan's bridge handler — declaring the address
# in netplan alongside `dhcp4: true` is what caused the reconcile loop recorded
# in docs/plans/setup-refactor.md.
#
# Does NOT touch systemd-resolved. Earlier Wisp versions (< 2026-04-18)
# configured resolved with MulticastDNS=resolve — clean that up manually on
# upgrade: remove /etc/systemd/resolved.conf.d/wisp-mdns.conf and restart
# systemd-resolved. See docs/spec/CONTAINERS.md for the full cleanup list.
#
# Idempotent. Safe to re-run. Must run as root.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root (use sudo)."
  exit 1
fi

echo "--- Container DNS (stub IP + resolv.conf) setup ---"

# bridge.sh must have run — 169.254.53.53 goes on br0, not on a NIC.
if [[ ! -d /sys/class/net/br0/bridge ]]; then
  echo "  Bridge br0 not found. Run scripts/linux/setup/bridge.sh first. Skipping."
  exit 0
fi

STUB_IP="169.254.53.53"
RESOLV_OUT="/var/lib/wisp/container-resolv.conf"
DROPIN_FILE="wisp-mdns-stub.conf"

# The .network unit systemd-networkd applied to br0, or empty when networkd
# isn't managing it (NetworkManager host, or a manually built bridge). Asking
# networkctl rather than guessing the path covers both layouts we produce:
# netplan renders /run/systemd/network/10-netplan-br0.network on Ubuntu, and
# bridge.sh writes /etc/systemd/network/90-wisp-br0.network directly on Arch.
# Capture first, match second — deliberately NOT a pipeline. awk's `exit` closes
# the pipe while networkctl is still writing, so networkctl dies of SIGPIPE (141);
# under `set -o pipefail` that becomes the pipeline's status and `set -e` aborts
# the whole script, silently, because stderr is discarded. `|| return 0` likewise
# keeps a non-zero networkctl (br0 unmanaged) from killing the run.
br0_network_unit() {
  command -v networkctl >/dev/null 2>&1 || return 0
  local status_output
  status_output="$(networkctl --no-pager status br0 2>/dev/null)" || return 0
  awk -F': +' '/^ *Network File:/ { print $2; exit }' <<<"$status_output"
}

# 1. Declare the stub IP so networkd owns it and re-applies it on every
#    reconfigure. Drop-ins live under /etc even when the unit is in /run.
NET_UNIT="$(br0_network_unit)"
if [[ "$NET_UNIT" == /*.network ]]; then
  DROPIN_DIR="/etc/systemd/network/$(basename "$NET_UNIT").d"
  mkdir -p "$DROPIN_DIR"
  cat > "${DROPIN_DIR}/${DROPIN_FILE}" <<EOF
# Generated by Wisp container-dns.sh — mDNS stub IP for Wisp's container DNS
# forwarder. Declared here so a systemd-networkd restart re-applies it instead
# of flushing it; a runtime-only address silently breaks all container DNS.
[Network]
Address=${STUB_IP}/32
EOF
  chmod 0644 "${DROPIN_DIR}/${DROPIN_FILE}"
  echo "  Wrote ${DROPIN_DIR}/${DROPIN_FILE} — networkd owns ${STUB_IP}/32."
  if ! networkctl reload 2>/dev/null; then
    echo "  WARNING: 'networkctl reload' failed; the drop-in applies on the next networkd restart."
  fi
else
  echo "  systemd-networkd does not manage br0 — ${STUB_IP}/32 stays runtime-only."
  echo "  It is re-asserted by wisp.service ExecStartPre on every service start."
fi

# 2. Assign the stub IP right now, for this boot. A no-op once the drop-in
#    above has been applied; the only assignment on non-networkd hosts.
# Same no-pipeline discipline as br0_network_unit: `grep -q` exits on its first
# match, and a SIGPIPE'd `ip` would make this condition read false, sending an
# already-present address down the `ip addr add` branch — which then fails and
# takes `set -e` with it.
BR0_ADDRS="$(ip -4 addr show dev br0 2>/dev/null || true)"
if [[ "$BR0_ADDRS" == *"${STUB_IP}/32"* ]]; then
  echo "  ${STUB_IP}/32 already present on br0."
else
  ip addr add "${STUB_IP}/32" dev br0 scope link
  echo "  Added ${STUB_IP}/32 to br0."
fi

# 3. Drop a ready-to-bind-mount resolv.conf for containers. The backend's
#    resolveContainerResolvConf() returns this path when the container's
#    bridge has the stub IP assigned.
mkdir -p /var/lib/wisp
cat > "$RESOLV_OUT" <<EOF
# Generated by Wisp container-dns.sh — bind-mounted into containers on br0.
nameserver ${STUB_IP}
options edns0
EOF
chmod 0644 "$RESOLV_OUT"
echo "  Wrote $RESOLV_OUT"

echo "Done. Containers on br0 route DNS through wisp's forwarder."
