#!/usr/bin/env bash
# Set up the stub IP + container resolv.conf used by Wisp's in-process DNS
# forwarder (backend/src/lib/linux/mdnsForwarder.js).
#
# How it works:
#   - Assign link-local 169.254.53.53/32 to br0. The wisp-backend process
#     binds UDP+TCP 53 on this IP (via CAP_NET_BIND_SERVICE) and answers
#     container DNS queries: `.local` names go to avahi over DBus,
#     everything else is forwarded to the host's upstream DNS.
#   - Drop a ready-to-bind-mount resolv.conf so Wisp containers on br0
#     use the stub IP as their sole nameserver.
#
# Does NOT touch systemd-resolved. Earlier Wisp versions (< 2026-04-18)
# configured resolved with MulticastDNS=resolve — clean that up manually on
# upgrade: remove /etc/systemd/resolved.conf.d/wisp-mdns.conf and restart
# systemd-resolved. See docs/spec/CONTAINERS.md for the full cleanup list.
#
# Idempotent. Safe to re-run. Must run as root.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root (use sudo)."
  exit 1
fi

echo "--- Container DNS (stub IP + resolv.conf) setup ---"

# bridge.sh must have run — 169.254.53.53 goes on br0, not on a NIC.
if [[ ! -d /sys/class/net/br0/bridge ]]; then
  echo "  Bridge br0 not found. Run scripts/linux/setup/bridge.sh first. Skipping."
  exit 0
fi

STUB_IP="169.254.53.53"
RESOLV_OUT="/var/lib/wisp/container-resolv.conf"

# 1. Assign the stub IP to br0 right now. Runtime-only — wisp-backend.service
#    has an ExecStartPre that re-applies this on every boot.
if ip -4 addr show dev br0 | grep -q "${STUB_IP}/32"; then
  echo "  ${STUB_IP}/32 already present on br0."
else
  ip addr add "${STUB_IP}/32" dev br0 scope link
  echo "  Added ${STUB_IP}/32 to br0."
fi

# 2. Drop a ready-to-bind-mount resolv.conf for containers. The backend's
#    resolveContainerResolvConf() returns this path when the container's
#    bridge has the stub IP assigned.
mkdir -p /var/lib/wisp
cat > "$RESOLV_OUT" <<EOF
# Generated by Wisp container-dns.sh — bind-mounted into containers on br0.
nameserver ${STUB_IP}
options edns0
EOF
chmod 0644 "$RESOLV_OUT"
echo "  Wrote $RESOLV_OUT"

echo "Done. Containers on br0 route DNS through wisp-backend's forwarder."
