#!/usr/bin/env bash
# Enable mDNS (.local) resolution for containers via systemd-resolved.
#
# How it works:
#   - Assign link-local 169.254.53.53/32 to br0 (stable, LAN-DHCP-independent).
#   - Tell systemd-resolved to also listen on that IP and query mDNS on behalf
#     of DNS clients that reach it (MulticastDNS=resolve — query-only so it
#     does not conflict with avahi-daemon, which owns mDNS responding on the
#     LAN via mdnsManager.js).
#   - Wisp containers on br0 get resolv.conf pointing at 169.254.53.53 and can
#     resolve .local names without any per-container configuration.
#
# Idempotent. Safe to re-run. Must run as root.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root (use sudo)."
  exit 1
fi

echo "--- Container mDNS (systemd-resolved) setup ---"

# Bail cleanly on hosts without systemd-resolved (rare, but possible on minimal images).
if ! command -v resolvectl >/dev/null 2>&1; then
  echo "  systemd-resolved (resolvectl) not found. Skipping; containers will not resolve .local."
  exit 0
fi

# bridge.sh must have run — 169.254.53.53 goes on br0, not on a NIC.
if [[ ! -d /sys/class/net/br0/bridge ]]; then
  echo "  Bridge br0 not found. Run scripts/linux/setup/bridge.sh first. Skipping."
  exit 0
fi

STUB_IP="169.254.53.53"
RESOLV_OUT="/var/lib/wisp/container-resolv.conf"
RESOLVED_DROPIN_DIR="/etc/systemd/resolved.conf.d"
RESOLVED_CONF="$RESOLVED_DROPIN_DIR/wisp-mdns.conf"
RESOLVED_UNIT_DROPIN_DIR="/etc/systemd/system/systemd-resolved.service.d"
RESOLVED_UNIT_DROPIN="$RESOLVED_UNIT_DROPIN_DIR/wisp-stub-ip.conf"

# 1. Assign the stub IP to br0 right now (idempotent).
if ip -4 addr show dev br0 | grep -q "${STUB_IP}/32"; then
  echo "  ${STUB_IP}/32 already present on br0."
else
  ip addr add "${STUB_IP}/32" dev br0 scope link
  echo "  Added ${STUB_IP}/32 to br0."
fi

# 2. Resolved drop-in: bind an extra listener on the stub IP and query mDNS.
#    MulticastDNS=resolve means resolved queries mDNS but does NOT respond —
#    avahi-daemon keeps ownership of publishing (mdnsManager.js relies on it).
mkdir -p "$RESOLVED_DROPIN_DIR"
cat > "$RESOLVED_CONF" <<EOF
# Generated by Wisp resolved-mdns.sh — container .local resolution.
[Resolve]
MulticastDNS=resolve
DNSStubListenerExtra=${STUB_IP}
EOF
echo "  Wrote $RESOLVED_CONF"

# 3. Service drop-in: ExecStartPre re-adds the stub IP on every resolved
#    restart so the bind to DNSStubListenerExtra does not fail after reboots
#    (br0 is created by the network manager; a reboot drops the runtime addr).
mkdir -p "$RESOLVED_UNIT_DROPIN_DIR"
cat > "$RESOLVED_UNIT_DROPIN" <<EOF
# Generated by Wisp resolved-mdns.sh — ensure stub IP exists before resolved binds.
[Service]
ExecStartPre=-/bin/sh -c '[ -d /sys/class/net/br0/bridge ] && (ip -4 addr show dev br0 | grep -q "${STUB_IP}/32" || ip addr add ${STUB_IP}/32 dev br0 scope link) || true'
EOF
echo "  Wrote $RESOLVED_UNIT_DROPIN"

# 4. Apply: reload units and restart resolved so both drop-ins take effect.
systemctl daemon-reload
if ! systemctl restart systemd-resolved; then
  echo "  WARNING: systemd-resolved failed to restart. Check 'journalctl -u systemd-resolved'."
  exit 1
fi

# 5. Per-link runtime setting: MulticastDNS=resolve on br0. Global default
#    covers other links too, but setting it explicitly here makes intent
#    obvious in 'resolvectl status'.
resolvectl mdns br0 resolve 2>/dev/null || true

# 6. Drop a ready-to-bind-mount resolv.conf for containers. The backend's
#    resolveContainerResolvConf() returns this path when the container's
#    bridge has the stub IP assigned.
mkdir -p /var/lib/wisp
cat > "$RESOLV_OUT" <<EOF
# Generated by Wisp resolved-mdns.sh — bind-mounted into containers on br0.
nameserver ${STUB_IP}
options edns0
EOF
chmod 0644 "$RESOLV_OUT"
echo "  Wrote $RESOLV_OUT"

echo "Done. Containers on br0 can now resolve .local via the host."
