/**
 * Avahi-backed mDNS registration for VM/container addresses (Linux).
 * Best-effort only: failures never break VM/container operations.
 *
 * Also maintains a shared `/etc/hosts` file bind-mounted into every Wisp
 * container (`CONTAINER_SHARED_HOSTS_FILE`). Avahi refuses to answer mDNS
 * queries originating on its own host, so same-host container `.local`
 * resolution short-circuits through this file instead of going out to mDNS.
 * LAN peers' `.local` names still resolve via the systemd-resolved stub.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import dbus from 'dbus-next';

import { CONTAINER_SHARED_HOSTS_FILE } from './containerManager/containerPaths.js';
import { sanitizeHostname, stripCidr } from '../mdnsHostname.js';

const AVAHI_BUS_NAME = 'org.freedesktop.Avahi';
const AVAHI_SERVER_PATH = '/';
const AVAHI_SERVER_IFACE = 'org.freedesktop.Avahi.Server';
const AVAHI_GROUP_IFACE = 'org.freedesktop.Avahi.EntryGroup';
const AVAHI_IF_UNSPEC = -1;
const AVAHI_PROTO_UNSPEC = -1;
const AVAHI_FLAG_DEFAULT = 0;

/** Baseline lines every container's /etc/hosts should have (mirrors typical runtime-generated /etc/hosts). */
const HOSTS_BASELINE = [
  '127.0.0.1       localhost',
  '::1             localhost ip6-localhost ip6-loopback',
  'ff02::1         ip6-allnodes',
  'ff02::2         ip6-allrouters',
];

const state = {
  bus: null,
  server: null,
  connected: false,
  /** key -> { group: EntryGroup iface, host: string, ip: string, fqdn: string } */
  entries: new Map(),
};

function buildHostsFileContent() {
  const lines = [
    '# Generated by Wisp mdnsManager — shared across all Wisp containers (bind-mounted read-only at /etc/hosts).',
    '# Rewritten on every mDNS register/deregister; do not edit.',
    '',
    ...HOSTS_BASELINE,
  ];
  if (state.entries.size) {
    lines.push('', '# Wisp mDNS entries');
    for (const { ip, fqdn } of state.entries.values()) {
      lines.push(`${ip}\t${fqdn}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Rewrite the shared hosts file from current in-memory state.
 * Writes in place (no rename-over) so the inode stays stable — every
 * container's read-only bind mount of this file is pinned to the original
 * inode at task start, so a rename would leave running containers looking at
 * the unlinked old file and never seeing new registrations.
 * Called at connect() time (so the file exists as a bind-mount source even
 * with no registrations and/or avahi unavailable) and after every
 * registerAddress/deregisterAddress. Best-effort: failures log a warning.
 */
async function writeHostsFile() {
  const dir = dirname(CONTAINER_SHARED_HOSTS_FILE);
  try {
    await mkdir(dir, { recursive: true });
  } catch {
    /* dir may exist with different perms; writeFile below will surface real errors */
  }
  try {
    await writeFile(CONTAINER_SHARED_HOSTS_FILE, buildHostsFileContent(), { encoding: 'utf8', mode: 0o644 });
  } catch (err) {
    console.warn(
      `[mdns] failed to write shared hosts file ${CONTAINER_SHARED_HOSTS_FILE}: ${err?.message || err}. ` +
      'Run: sudo ./scripts/linux/setup/dirs.sh <deploy-user>',
    );
  }
}

async function ensureConnected() {
  if (state.connected && state.server) return true;
  try {
    if (!state.bus) state.bus = dbus.systemBus();
    const obj = await state.bus.getProxyObject(AVAHI_BUS_NAME, AVAHI_SERVER_PATH);
    state.server = obj.getInterface(AVAHI_SERVER_IFACE);
    state.connected = true;
    return true;
  } catch (err) {
    console.warn('[mdns] Avahi connection failed:', err?.message || err);
    state.connected = false;
    state.server = null;
    return false;
  }
}

async function createGroup() {
  const groupPath = await state.server.EntryGroupNew();
  const obj = await state.bus.getProxyObject(AVAHI_BUS_NAME, groupPath);
  return obj.getInterface(AVAHI_GROUP_IFACE);
}

export async function connect() {
  await writeHostsFile();
  await ensureConnected();
}

export async function disconnect() {
  for (const entry of state.entries.values()) {
    try {
      await entry.group.Free();
    } catch {
      /* best effort on shutdown */
    }
  }
  state.entries.clear();
  if (state.bus) {
    try {
      state.bus.disconnect();
    } catch {
      /* best effort */
    }
  }
  state.bus = null;
  state.server = null;
  state.connected = false;
}

export async function registerAddress(key, preferredName, ipOrCidr) {
  const ip = stripCidr(ipOrCidr);
  const host = sanitizeHostname(preferredName);
  if (!key || !host || !ip) return null;
  if (!(await ensureConnected())) return null;

  const current = state.entries.get(key);
  if (current && current.host === host && current.ip === ip) return current.fqdn;
  if (current) {
    try {
      await current.group.Free();
    } catch {
      /* free stale entry */
    }
    state.entries.delete(key);
  }

  try {
    const group = await createGroup();
    const fqdn = `${host}.local`;
    await group.AddAddress(
      AVAHI_IF_UNSPEC,
      AVAHI_PROTO_UNSPEC,
      AVAHI_FLAG_DEFAULT,
      fqdn,
      ip,
    );
    await group.Commit();
    state.entries.set(key, { group, host, ip, fqdn });
    await writeHostsFile();
    return fqdn;
  } catch (err) {
    console.warn('[mdns] registerAddress failed:', err?.message || err);
    return null;
  }
}

export async function deregisterAddress(key) {
  const current = state.entries.get(key);
  if (!current) return;
  state.entries.delete(key);
  try {
    await current.group.Free();
  } catch {
    /* best effort */
  }
  await writeHostsFile();
}

export function getRegisteredHostname(key) {
  return state.entries.get(key)?.fqdn || null;
}
